### ISSUE TITLE
Support or switch to Python 3?

### ISSUE THREAD

**Issue by dieggsy** [iraikov/chicken-pyffi#2]
Are there any plans to support or switch to python 3? Python 2's EOL is looming: https://pythonclock.org/

**Comment by iraikov** [comment]
Yes, let me test pyffi with py3 and see what needs to be done.

**Comment by iraikov** [comment]
Release 3.9 adds support for python 3.

**Comment by dieggsy** [comment]
That's awesome! Thank you!
