### ISSUE TITLE
error converting inexact integers

### ISSUE THREAD

**Issue by dakling** [iraikov/chicken-pyffi#5]
Hi, 

I noticed that something like `(py-pbject-to 1.0)` fails with 
```
=> Error: (#f) "bad argument type - not an integer": (1.0)
```
while e.g. `(py-pbject-to 1)` and `(py-pbject-to 0.3)` work as expected. Could this perhaps be fixed by changing
```
(define (py-object-to value)
  (cond
   ((integer? value)  (translate-to-foreign value py-int))
  ...
```
to 
```
(define (py-object-to value)
  (cond
   ((integer? value)  (translate-to-foreign (inexact->exact value) py-int))
  ...
```
? Alternatively,
```
(define (py-object-to value)
  (cond
   ((exact-integer? value)  (translate-to-foreign value py-int))
  ...
```
could also work, though I assume that the first one would be nicer. Not sure if any of these suggestions would cause any problems, though I can't think of any.

Best regards!

**Comment by iraikov** [comment]
Hello,
Thanks for reporting this issue. It was a bit surprising to me that (integer? 1.0) returns true, but semantically it is correct of course.  Your solutions seem ok, but wouldn't it be unexpected if py-object-to returns integer on a floating point number such as 1.0. Another possibility is that py-object-to could check for inexact before checking for integer, and convert that to a py-float. What do you think about this?

**Comment by dakling** [comment]
Yes, that was surprising for me as well :D
Now that I think more about it, you are probably correct that it would be more natural if 1.0 was converted to a floating point number in python. Therefore, your suggestion is probably better (which should be equivalent to my second suggestion, right?)

**Comment by iraikov** [comment]
I have pushed the change to master, let me know if it works for you.

**Comment by dakling** [comment]
Not sure if I am missing something, but `(py-object-from (py-object-to 1))` now seems to return 1.0 instead of 1. On the other hand, when using
```
(define (py-object-to value)
  (cond
   ((exact-integer? value)  (translate-to-foreign value py-int))
   ((real? value)     (translate-to-foreign value py-float))
   ((alist? value)    (translate-to-foreign value py-dict))
   ((list? value)     (if (eq? 'ascii (car value)) 
			  (translate-to-foreign (cadr value) py-ascii)
			  (translate-to-foreign value py-list)))
   ((string? value)   (translate-to-foreign value py-unicode))
   ((vector? value)   (translate-to-foreign value py-tuple))
   ((blob? value)     (translate-to-foreign value py-buffer))
   ((boolean? value)  (translate-to-foreign value py-bool))
   ((pointer? value)  value)
   (else (pyffi:error 'py-object-to "invalid value " value))))
```
where the only change compared to the original code is `exact-integer?` instead of `integer?`, the results make more sense to me:
```
(py-object-from (py-object-to 1))
=> 1
(py-object-from (py-object-to 1.0))
=> 1.0
(py-object-from (py-object-to 0.3))
=> 0.3
```

**Comment by iraikov** [comment]
Hm, you are right, I tried to be too clever with inexact? but I see now it will cause problems with round-trip conversions. I have changed to using exact-integer? as you suggested.

**Comment by dakling** [comment]
awesome, thanks!
