### ISSUE TITLE
Difficulty installing on macOS Catalina

### ISSUE THREAD

**Issue by spencerking** [iraikov/chicken-pyffi#6]
I'm having some issues installing on macOS Catalina. I've tried specifying the paths to my Python installation like so
```
PYTHON_CFLAGS=-I/Users/spencerking/opt/anaconda3/bin/python3 PYTHON_LFLAGS=-L/Users/spencerking/opt/anaconda3/lib PYTHON_LIBS=-lpython3.7 chicken-install pyffi
```

But am getting:

```fatal error: 'Python.h' file not found```

**Comment by iraikov** [comment]
Hi Spencer, thanks for reporting this issue. I will take a closer look shortly, but it looks like your PYTHON_CFLAGS -I setting is pointing to the actual Python executable, not to the include directory. You will need to make sure that the directory following -I actually contains Python.h. (I would guess .../anaconda3/include or .../anaconda3/include/python).

**Comment by spencerking** [comment]
Well, I'm getting closer. I ran 

```PYTHON_CFLAGS=-I/Users/spencerking/opt/anaconda3/include/python3.7m PYTHON_LFLAGS=-L/Users/spencerking/opt/anaconda3/lib PYTHON_LIBS=-lpython3.7 chicken-install pyffi```

And I'm getting: `ld: library not found for -lpython3.7`

I've looked in `/Users/spencerking/opt/anaconda3/lib` and see a `python3.7` directory.

**Comment by iraikov** [comment]
Hi Spencer,
If there is a directory /Users/spencerking/opt/anaconda3/lib/python3.7 then your PYTHON_LFLAGS should probably be:
PYTHON_LFLAGS=-L/Users/spencerking/opt/anaconda3/lib/python3.7

With your current settings, the linker will be looking for the python library in  .../opt/anaconda3/lib and likely not finding it.

**Comment by Dima-369** [comment]
I also struggled with the same error, although my Python 3.9 was installed through Homebrew, but I found a good solution in the end:

Run the command below.
Instead of `python3`, `python` can be used as well, depending on which Python version is required.

```bash
python3 -c "from sysconfig import get_paths; import pprint; pprint.pprint(get_paths())"
```

This returns something like:

```bash
{'data':        '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9',
 'include':     '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9',
 'platinclude': '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9',
 'platlib':     '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages',
 'platstdlib':  '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
 'purelib':     '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages',
 'scripts':     '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/bin',
 'stdlib':      '/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9'}
```

From that output `include` (for `PYTHON_CFLAGS`) and `stdlib` (for `PYTHON_LFLAGS`) are of interest. With this info the following command finally succeeded:

```bash
PYTHON_CFLAGS=-I/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9 \
PYTHON_LFLAGS=-L/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib \
PYTHON_LIBS=-lpython3.9 \
chicken-install pyffi
```

---

Maybe this info could be added to the README?
I am sure it is helpful for others as well :)

**Comment by iraikov** [comment]
Hi Dimitri,
Thanks for your example, I have added it to the README.
