### ISSUE TITLE
Feature request: support complex numbers

### ISSUE THREAD

**Issue by dieggsy** [iraikov/chicken-pyffi#9]
Since both python and scheme have built-in support for complex numbers, it'd be nice to automatically convert between these.

**Comment by iraikov** [comment]
Hi Diego,
Thanks for the suggestion.  I have added initial support for complex numbers, please try it out and let me know if it works for you.

**Comment by dieggsy** [comment]
Thanks! That seems to be working nicely as far as I can tell.
